// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MkeAlerts.Web.Data;
using NetTopologySuite.Geometries;

namespace MkeAlerts.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("85f00d40-d578-4988-9f22-4d023175f852"),
                            RoleId = new Guid("7e3f1477-2377-4e5f-b02c-a13b9795e157")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Accounts.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e3f1477-2377-4e5f-b02c-a13b9795e157"),
                            ConcurrencyStamp = "19663565-a927-4ef5-aa56-29fe2cd27740",
                            Name = "SiteAdmin",
                            NormalizedName = "SITEADMIN"
                        });
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85f00d40-d578-4988-9f22-4d023175f852"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2502828-f0aa-4f7f-a11c-67b917d4895a",
                            Email = "cwilson@mkealerts.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CWILSON@MKEALERTS.COM",
                            NormalizedUserName = "CWILSON@MKEALERTS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAEzcDne6YcO33ojupDLj5+2ot/ZKL5rQ01nCdO7NrWc7M8C7B4LoUa7ad8xqyDqVw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "HALICG3767VFP5B5FTAF4P2X7AEHFSWZ",
                            TwoFactorEnabled = false,
                            UserName = "cwilson@mkealerts.com"
                        });
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Accounts.ExternalCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ExternalCredentials");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.AppHealth.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessages")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Incidents.Crime", b =>
                {
                    b.Property<string>("IncidentNum")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<decimal>("ALD")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arson")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssaultOffense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Burglary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriminalDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Homicide")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastGeocodeAttempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<int>("LockedVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MaxLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<decimal>("NSP")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("POLICE")
                        .HasColumnType("TEXT");

                    b.Property<Point>("Point")
                        .HasColumnType("POINT");

                    b.Property<DateTime>("ReportedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReportedMonth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReportedYear")
                        .HasColumnType("TEXT");

                    b.Property<int>("Robbery")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RoughX")
                        .HasColumnType("REAL");

                    b.Property<double>("RoughY")
                        .HasColumnType("REAL");

                    b.Property<int>("SexOffense")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TRACT")
                        .HasColumnType("TEXT");

                    b.Property<int>("Theft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleTheft")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WARD")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponUsed")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<decimal>("ZIP")
                        .HasColumnType("TEXT");

                    b.HasKey("IncidentNum");

                    b.HasIndex("ReportedDateTime");

                    b.ToTable("Crimes");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Incidents.FireDispatchCall", b =>
                {
                    b.Property<string>("CFS")
                        .HasColumnType("TEXT")
                        .HasMaxLength(12);

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<string>("Apt")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Disposition")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("GEOMETRY");

                    b.Property<DateTime?>("LastGeocodeAttempt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MaxLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<string>("NatureOfCall")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<DateTime>("ReportedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("CFS");

                    b.HasIndex("ReportedDateTime");

                    b.ToTable("FireDispatchCalls");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Incidents.FireDispatchCallType", b =>
                {
                    b.Property<string>("NatureOfCall")
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<bool>("IsCritical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFire")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMedical")
                        .HasColumnType("INTEGER");

                    b.HasKey("NatureOfCall");

                    b.ToTable("FireDispatchCallTypes");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Incidents.PoliceDispatchCall", b =>
                {
                    b.Property<string>("CallNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(12);

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("District")
                        .HasColumnType("INTEGER");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("GEOMETRY");

                    b.Property<DateTime?>("LastGeocodeAttempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<double>("MaxLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MaxLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<string>("NatureOfCall")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<DateTime>("ReportedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.HasKey("CallNumber");

                    b.HasIndex("ReportedDateTime");

                    b.ToTable("PoliceDispatchCalls");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Incidents.PoliceDispatchCallType", b =>
                {
                    b.Property<string>("NatureOfCall")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<bool>("IsCritical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDrug")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOtherCrime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProperty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTraffic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViolent")
                        .HasColumnType("INTEGER");

                    b.HasKey("NatureOfCall");

                    b.ToTable("PoliceDispatchCallTypes");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Places.Address", b =>
                {
                    b.Property<int>("ADDRESS_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ALT_ID")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<int>("BUILDING_I")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CLINEID")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("COMMENT")
                        .HasColumnType("TEXT")
                        .HasMaxLength(140);

                    b.Property<string>("DD_LAT")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("DD_LONG")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("DIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("FULLADDR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<string>("HOUSENO")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<string>("HOUSESX")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MAILABLE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MUNI")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<double>("MaxLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MaxLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<int>("OBJECTID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PDIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<Point>("Point")
                        .HasColumnType("POINT");

                    b.Property<string>("SOURCE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(36);

                    b.Property<string>("SOURCE_ID")
                        .HasColumnType("TEXT")
                        .HasMaxLength(21);

                    b.Property<string>("STREET")
                        .HasColumnType("TEXT")
                        .HasMaxLength(19);

                    b.Property<string>("STTYPE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.Property<string>("TAG")
                        .HasColumnType("TEXT")
                        .HasMaxLength(41);

                    b.Property<string>("TAXKEY")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("UNIT")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("X")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("Y")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("ZIP_CODE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(9);

                    b.HasKey("ADDRESS_ID");

                    b.HasIndex("TAXKEY");

                    b.HasIndex("DIR", "STREET", "STTYPE", "HouseNumber");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Places.CommonParcel", b =>
                {
                    b.Property<int>("MAP_ID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MaxLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<Geometry>("Outline")
                        .HasColumnType("GEOMETRY");

                    b.HasKey("MAP_ID");

                    b.HasIndex("MaxLat");

                    b.HasIndex("MaxLng");

                    b.HasIndex("MinLat");

                    b.HasIndex("MinLng");

                    b.ToTable("CommonParcels");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Places.Parcel", b =>
                {
                    b.Property<string>("TAXKEY")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<double>("ACRES")
                        .HasColumnType("REAL");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.Property<int>("ASSESSEDVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ASSESSMENT")
                        .HasColumnType("TEXT")
                        .HasMaxLength(88);

                    b.Property<string>("CLASS")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("COMMENT")
                        .HasColumnType("TEXT")
                        .HasMaxLength(84);

                    b.Property<string>("CONDO_NAME")
                        .HasColumnType("TEXT")
                        .HasMaxLength(74);

                    b.Property<string>("DESCRIPTIO")
                        .HasColumnType("TEXT")
                        .HasMaxLength(23);

                    b.Property<string>("DWELLING_C")
                        .HasColumnType("TEXT")
                        .HasMaxLength(8);

                    b.Property<string>("EXM_CLASS_")
                        .HasColumnType("TEXT")
                        .HasMaxLength(76);

                    b.Property<string>("EXM_TYP")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3);

                    b.Property<string>("EXM_TYP_DE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(94);

                    b.Property<int>("FAIR_MKT_V")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GIS_ACRES")
                        .HasColumnType("REAL");

                    b.Property<double>("GROSS_TAX")
                        .HasColumnType("REAL");

                    b.Property<string>("HOUSENR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("HOUSENRHI")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("HOUSENRSFX")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3);

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseNumberHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IMPVALUE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LANDVALUE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LEGALDESCR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(254);

                    b.Property<int>("MAP_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MCD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("MUNINAME")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<double>("NET_TAX")
                        .HasColumnType("REAL");

                    b.Property<int>("OBJECTID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OVERLAP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OWNERADDR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(49);

                    b.Property<string>("OWNERCTYST")
                        .HasColumnType("TEXT")
                        .HasMaxLength(27);

                    b.Property<string>("OWNERNAME1")
                        .HasColumnType("TEXT")
                        .HasMaxLength(84);

                    b.Property<string>("OWNERNAME2")
                        .HasColumnType("TEXT")
                        .HasMaxLength(84);

                    b.Property<string>("OWNERNAME3")
                        .HasColumnType("TEXT")
                        .HasMaxLength(28);

                    b.Property<string>("OWNERZIP")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("PARCELNO")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("PARCEL_DES")
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<string>("PARCEL_KEY")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("PARCEL_TYP")
                        .HasColumnType("TEXT")
                        .HasMaxLength(13);

                    b.Property<string>("PAR_ZIP")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("PAR_ZIP_EX")
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.Property<string>("POSTOFFICE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<int>("RECID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RECSOURCE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(7);

                    b.Property<string>("SCHOOL_DIS")
                        .HasColumnType("TEXT")
                        .HasMaxLength(41);

                    b.Property<string>("SCHOOL_ID")
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.Property<string>("SOURCE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(39);

                    b.Property<string>("STREETDIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("STREETNAME")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("STREETTYPE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.Property<string>("SUFFIXDIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("TAX_INFO_U")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<int>("TAX_YR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UNITNUMBER")
                        .HasColumnType("TEXT")
                        .HasMaxLength(8);

                    b.Property<string>("UNIT_TYPE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(7);

                    b.Property<string>("ZONING_COD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("ZONING_DES")
                        .HasColumnType("TEXT")
                        .HasMaxLength(29);

                    b.Property<string>("ZONING_URL")
                        .HasColumnType("TEXT")
                        .HasMaxLength(88);

                    b.HasKey("TAXKEY");

                    b.HasIndex("MAP_ID");

                    b.HasIndex("STREETDIR", "STREETNAME", "STREETTYPE", "HouseNumber");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Places.Street", b =>
                {
                    b.Property<int>("CLINEID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("COMMENT")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("DATE_CHANG")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("DIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("FCC")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3);

                    b.Property<string>("HIGH")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("HIGHWAY")
                        .HasColumnType("TEXT")
                        .HasMaxLength(16);

                    b.Property<string>("LEFTFR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("LEFTTO")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("LOW")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("L_MCD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<int>("LeftNumberHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeftNumberLow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MUNI")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<double>("MaxLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MaxLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLat")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<double>("MinLng")
                        .HasColumnType("decimal(13, 10)");

                    b.Property<int>("OBJECTID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OWNER")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<Geometry>("Outline")
                        .HasColumnType("GEOMETRY");

                    b.Property<string>("PDIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("RIGHTFR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("RIGHTTO")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<string>("R_MCD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<int>("RightNumberHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightNumberLow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SHIELD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("SOURCE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("STREET")
                        .HasColumnType("TEXT")
                        .HasMaxLength(24);

                    b.Property<string>("STTYPE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.HasKey("CLINEID");

                    b.HasIndex("MaxLat");

                    b.HasIndex("MaxLng");

                    b.HasIndex("MinLat");

                    b.HasIndex("MinLng");

                    b.HasIndex("DIR", "STREET", "STTYPE");

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Subscriptions.DispatchCallSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DispatchCallType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HOUSE_NR")
                        .HasColumnType("INTEGER");

                    b.Property<Point>("Point")
                        .HasColumnType("POINT");

                    b.Property<string>("SDIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("STREET")
                        .HasColumnType("TEXT")
                        .HasMaxLength(18);

                    b.Property<string>("STTYPE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("DispatchCallSubscriptions");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Subscriptions.PickupDatesSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LADDR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("NextGarbagePickupDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextGarbagePickupNotification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRecyclingPickupDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRecyclingPickupNotification")
                        .HasColumnType("TEXT");

                    b.Property<string>("SDIR")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1);

                    b.Property<string>("SNAME")
                        .HasColumnType("TEXT")
                        .HasMaxLength(18);

                    b.Property<string>("STYPE")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("PickupDateSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Accounts.ExternalCredential", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", "ApplicationUser")
                        .WithMany("ExternalCredentials")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Places.Address", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Places.Parcel", "Parcel")
                        .WithMany("Addresses")
                        .HasForeignKey("TAXKEY");
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Places.Parcel", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Places.CommonParcel", "CommonParcel")
                        .WithMany("Parcels")
                        .HasForeignKey("MAP_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Subscriptions.DispatchCallSubscription", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", "ApplicationUser")
                        .WithMany("DispatchCallSubscriptions")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MkeAlerts.Web.Models.Data.Subscriptions.PickupDatesSubscription", b =>
                {
                    b.HasOne("MkeAlerts.Web.Models.Data.Accounts.ApplicationUser", "ApplicationUser")
                        .WithMany("PickupDateSubscriptions")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
