--drop index [SpatialIndex-Outline] ON [dbo].[Locations]

USE [MkeAlerts]
GO

SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

GO

/*
CREATE SPATIAL INDEX [SpatialIndex-Outline] ON [dbo].[Locations]
(
	[Outline]
)USING  GEOMETRY_AUTO_GRID 
WITH (
CELLS_PER_OBJECT = 256, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
*/

CREATE SPATIAL INDEX [SpatialIndex-Outline] 
   ON Locations(Outline)  
   WITH ( BOUNDING_BOX = ( 42.4, -88.0, 43.2, -87.6),
        GRIDS = ( LEVEL_1 = LOW, LEVEL_2 = MEDIUM, LEVEL_3 = MEDIUM, LEVEL_4 = HIGH ),
		CELLS_PER_OBJECT = 256
        );  