INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('AIRCRFT DWN', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BOMB THREAT', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('DEMONSTRATION', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('EXPLOSION', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('EXPLOSIVES', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('GAS LEAK', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('HAZ WASTE MAT', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('HOSTAGE SIT', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOST CHILD', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MISSING REPT CRIT', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MOST WANTED (MKE)', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TORNADO TCHDWN', 1, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ABDUCTION', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BATTERY', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BATTERY CUTTING', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BATTERY DV', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BB GUN CMPLNT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('DEAD ON ENTRY', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FIGHT', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('IND EXPOSURE', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('OFFICER SHOT', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('RECK USE OF WEAP', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ROBB ST ARM', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ROBBERY ARMED', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SEX ASST', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SHOOTING', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SHOTS FIRED', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SHOTSPOTTER', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUBJ WANTED', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUBJ WITH GUN', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUBJ WITH WEAPON', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('THREAT', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('THREAT SCHOOL', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRBL W/JUV', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRBL W/SUBJ', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('VIOL REST ORDER', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BURG AUD/SIL', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BURG/AUD GOVT', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BURG/AUD RESI', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ENTRY', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ENTRY TO AUTO', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FIRE', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('HOLDUP ALARM', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PROPERTY DAMAGE', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ROBBERY', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('STOLEN VEH', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('STOLEN VEHICLE', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUSP PACKAGE/DEVICE', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUSP PERS/AUTO', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('THEFT', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('THEFT FROM PERSN', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('THEFT VEHICLE', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRESPASSER', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('DRUG DEALING', 0, 0, 0, 1, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('DUI', 0, 0, 0, 1, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('METH LAB', 0, 0, 0, 1, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('OVERDOSE', 0, 0, 0, 1, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('911 ABUSE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ABAND/PROP WEAPO', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ABAND/STOLEN PRO', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ACC PDO', 0, 0, 0, 0, 1)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ACC PDO HWY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ACC PI', 0, 0, 0, 0, 1)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ACC PI HWY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ACC UNKN INJ', 0, 0, 0, 0, 1)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ACC UNKN INJ HWY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ADDL INFO', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ALARM ON BUS', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ALTERED CURRENCY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ANIMAL BITE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ASSIGN-ADMN MPD', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ASSIGNMENT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ASSIST OFFICER', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ASST FIRE/AMB', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BOAT STOP', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BUS INVESTIGATIO', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BUSINESS CHECK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CALL BY (10-21)', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CALL FOR POLICE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CAR CHANGE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CAR CHECK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CHILD ABUSE', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CHILD CUSTODY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CHILD NEGLECT', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CITIZEN CONTACT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CITIZEN CONVEY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('COMMUNITY MTNG', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CONT DEL MINOR', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CONVEY PROP', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CONVEY PROPERTY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('COURT DUTY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CRUELTY ANIMAL', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ESCORT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ESP TARGET ESCORT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FALSE FIRE ALARM', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FAMILY TROUBLE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FIREWORKS', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FLOODING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FOLLOW UP', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FOOT PURSUIT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FORGERY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FRAUD', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('FRAUD CREDIT CARD', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('GAMBLING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('GANG', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('GPS MONITORING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('GRAFFITI', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('HOME VISIT DV', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('HOSPITAL GUARD', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('HOSPITAL TO MCMH', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('INJ PERSON/SICK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('INTERNET CRIMES', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('INVESTIGATION', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ISS WORTH CHECK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('JUV CONVEY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LANDLORD/TEN TRB', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOCKOUT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOITERING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOOSE ANIMAL', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOUD MUSIC – BUS', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOUD MUSIC – OTHER', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOUD MUSIC – RES', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('LOUD MUSIC – VEH', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MAIL-RUN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MARINE VIOL', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MED RUN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MEET GOVT AGENCY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MEET PD/OTHER', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MFD OTHER', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MFD SECURITY', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MISSING CHECK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MISSING REPT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MISSING RETURN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MO', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MPD MON ALARM', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('MPD MONITORED ALARM', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('NETWORK CRIMINAL', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('NOISE NUISANCE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('NON PURSUIT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('NON PURSUIT NO P', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('NOTIFICATION', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('OPEN HYDRANT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('OUT OF SERVICE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('OVERTURNED BOAT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PARK AND WALK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PARKING TROUBLE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PATROL', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PD/OTHER IN MKE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PHONE CALL CMPLNT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PHONE CALL COMPL', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PHOTO ASSIGN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PICKUP PARTNER', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PRISONER BOOKING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PRISONER TRANS', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PROB_PAROL_CK_RQ', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PROBATION/PAROLE', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PROPERTY PICKUP', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('PROWLERS', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('RECKLESS VEHICLE', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('RECOVERED PROP', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('RECOVERED VEH', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('REPORT TO (10-22)', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('REPORTS', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('RETURN STATION', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SCHL MONITORING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SCHOOL', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SCHOOL CROSSING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SEND SQUAD/MEET', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SHOPLIFTER', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SOLICITING', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SPECIAL ASSIGN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUBJ IN WATER', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUBJ STOP', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUICIDE ATTEMPT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUSPICIOUS-OTH', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TAVERN CHECK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TAVERN VIOLATION', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRAFFIC CONTROL', 0, 0, 0, 0, 1)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRAFFIC HAZARD', 0, 0, 0, 0, 1)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRAFFIC LASER', 0, 0, 0, 0, 1)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRAFFIC STOP', 0, 0, 0, 0, 1)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('TRUANT', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('UNDEFINED', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('VACANT HOUSE CHK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('VEH MAINTAIN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('VEHICLE PURSUIT', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('WATER MAIN BRK', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('WELFARE CITIZEN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('WIRES DOWN', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('911 ABUSE CONFIR', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ASSIST FIRE/AMB', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('BURG/AUD BUSINES', 0, 0, 1, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('CHILD ENTICEMENT', 0, 1, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('ESP TARGET ESCOR', 0, 0, 0, 0, 0)
INSERT INTO PoliceDispatchCallTypes (NatureOfCall, IsCritical, IsViolent, IsProperty, IsDrug, IsTraffic) VALUES ('SUSP PKG/DEVICE', 0, 0, 0, 0, 0)

INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Carbon Monoxide', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Elevator Stuck', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Smoke Condition', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Natural Gas Leak', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Petroleum Spill', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Tree Fire', 0, 1, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Water Leak', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Forcible Entry', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('EMS', 0, 0, 1)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Flush', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Lock Out', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Auto Extrication', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Rubbish Fire', 0, 1, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Alarm Sounding', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Limited Response', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Building Fire', 1, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Auto Fire', 1, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Wires Down', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Electrical Trouble', 0, 0, 0)
INSERT INTO FireDispatchCallTypes (NatureOfCall, IsCritical, IsFire, IsMedical) VALUES ('Appliance Fire', 0, 1, 0)
